# Use root/example as user/password credentials
version: '3.2'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: vision
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db:/data/db
    container_name: 'mongodb'
    ports:
      - '27017:27017'
  
